apiVersion: apps/v1 
kind: Deployment
metadata:
  name: jmeter-master-c
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
    spec:
      containers:
      - name: jmmaster
        image: cbpuneethchanda/jmmaster
        imagePullPolicy: IfNotPresent
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - name: loadtest
            mountPath: /load_test
        ports:
        - containerPort: 60000
      volumes:
      - name: loadtest 
        configMap:
          name: masterconfig